updated my git hooks

diff --git a/git_template/hooks/pre-push b/git_template/hooks/pre-push
--- a/git_template/hooks/pre-push
+++ b/git_template/hooks/pre-push
@@ -19,24 +19,45 @@
 # This sample shows how to prevent push of commits where the log message starts
 # with "WIP" (work in progress).
 
-#!/bin/sh
+#!/bin/bash
+
+validate_last_command() {
+	if [ $? -ne 0 ]; then
+		echo "Unable to commit, validation failure"
+		exit 1
+	fi
+}
+
+build_maven() {
+    local MVN=`which mvn`
+    
+    $MVN clean verify
+    validate_last_command
+}
+
+build_ant() {
+    local ANT=`which ant`
+
+    $ANT build-parallel
+    validate_last_command
+}
+
+build_grunt() {
+    local GRUNT=`which grunt`
+
+    $GRUNT
+    validate_last_command
+}
+
+git stash
 
 if [ -e "pom.xml" ]; then
-	mvn clean verify
-
-	if [ $? -ne 0 ]; then
-		echo "Unable to commit, validation failure"
-		exit 1
-	fi
+    build_maven
 fi
 
-if [ -e "build.xml"]; then
-	ant build-parallel
-
-	if [ $? -ne 0 ]; then
-		echo "Unable to commit, validation failure"
-		exit 1
-	fi
+if [ -e "build.xml" ]; then
+    build_ant
 fi
 
+git stash pop
 exit 0
